#ifndef KEYPAD_CONF_H
#define KEYPAD_CONF_H

#include <libopencm3/stm32/gpio.h>

#define KEYPAD_BANK_ROW GPIOB
#define KEYPAD_ROW_ALL (KEYPAD_ROW1 | KEYPAD_ROW2 | KEYPAD_ROW3 | KEYPAD_ROW4)
#define KEYPAD_ROW4 GPIO6
#define KEYPAD_ROW3 GPIO7
#define KEYPAD_ROW2 GPIO8
#define KEYPAD_ROW1 GPIO9

#define KEYPAD_BANK_COL GPIOA
#define KEYPAD_COL_ALL (KEYPAD_COL1 | KEYPAD_COL2 | KEYPAD_COL3 | KEYPAD_COL4)
#define KEYPAD_COL4 GPIO3
#define KEYPAD_COL3 GPIO2
#define KEYPAD_COL2 GPIO1
#define KEYPAD_COL1 GPIO0

#endif